# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_box_cutter <- function(json_info, mins, maxs) {
    .Call('neurostr_c_box_cutter', PACKAGE = 'neurostr', json_info, mins, maxs)
}

c_branch_feature_extractor <- function(json_info, omitapical, omitaxon, omitdend, correct) {
    .Call('neurostr_c_branch_feature_extractor', PACKAGE = 'neurostr', json_info, omitapical, omitaxon, omitdend, correct)
}

c_cut_node_feature_extractor <- function(json_info, id_nodes, omitapical, omitaxon, omitdend, correct, remove_zjumps) {
    .Call('neurostr_c_cut_node_feature_extractor', PACKAGE = 'neurostr', json_info, id_nodes, omitapical, omitaxon, omitdend, correct, remove_zjumps)
}

c_get_cut_nodes <- function(json_info) {
    .Call('neurostr_c_get_cut_nodes', PACKAGE = 'neurostr', json_info)
}

c_get_root_neurite_nodes <- function(json_info) {
    .Call('neurostr_c_get_root_neurite_nodes', PACKAGE = 'neurostr', json_info)
}

c_get_terminal_nodes <- function(json_info) {
    .Call('neurostr_c_get_terminal_nodes', PACKAGE = 'neurostr', json_info)
}

c_neurite_feature_extractor <- function(json_info, omitapical, omitaxon, omitdend, correct) {
    .Call('neurostr_c_neurite_feature_extractor', PACKAGE = 'neurostr', json_info, omitapical, omitaxon, omitdend, correct)
}

c_neurite_feature_extractor_prueba <- function(json_info, omitapical, omitaxon, omitdend, correct, remove_zjumps) {
    .Call('neurostr_c_neurite_feature_extractor_prueba', PACKAGE = 'neurostr', json_info, omitapical, omitaxon, omitdend, correct, remove_zjumps)
}

c_neuro_converter2 <- function(ifile, correct, eps) {
    .Call('neurostr_c_neuro_converter2', PACKAGE = 'neurostr', ifile, correct, eps)
}

c_neuro_converter <- function(ifile, correct, eps) {
    .Call('neurostr_c_neuro_converter', PACKAGE = 'neurostr', ifile, correct, eps)
}

c_node_feature_extractor <- function(json_info, omitapical, omitaxon, omitdend, correct, remove_zjumps) {
    .Call('neurostr_c_node_feature_extractor', PACKAGE = 'neurostr', json_info, omitapical, omitaxon, omitdend, correct, remove_zjumps)
}

c_simulated_position <- function(json_info, new_nodes, is_bifurcation, init_id, omitapical, omitaxon, omitdend, correct, remove_zjumps) {
    .Call('neurostr_c_simulated_position', PACKAGE = 'neurostr', json_info, new_nodes, is_bifurcation, init_id, omitapical, omitaxon, omitdend, correct, remove_zjumps)
}

